### PR TITLE
Add a rule in Representation and Adaptation set checking

### PR DESCRIPTION
**Pull request by joywelt**
For an IOP test vector, when sidx is present, either the indexRange should be specified or the element @RepresentationIndex should be present.

### CODE REVIEW

**Comment by joywelt** [comment]
Update: fixed wrong error message of Segmenttimeline and Dynamic

**Comment by joywelt** [comment]
Update: fixed wrong error message of Segmenttimeline and Dynamic

**Comment by waqarz** [comment]
There is no corresponding PR for the executable https://github.com/Dash-Industry-Forum/Conformance-and-reference-source/

**Comment by joywelt** [comment]
PR added https://github.com/Dash-Industry-Forum/Conformance-and-reference-source/pull/25

**Comment by joywelt** [comment]
MPD check tool modified

**Comment by joywelt** [comment]
Fixed issue #152 about wrong number of segments.

**Pull request merged**
