### PR TITLE
Changes done in the framework. The client-server response model is changed.

### PR DESCRIPTION
**Pull request by niteeshbhat**
Client(JS) sends MPD to server and tracks conformance results through progress.xml.
1)conformancetest.php changed to track and display results on the webpage.
2)mpdprocessing.php  changed to run conformance independently
3)datadownload.php changed to read progress from global progress variable.
4)crossvalidation.php changed to fix the bug of not opening Adapt infofile.txt for the new framework.

### CODE REVIEW

**Comment by niteeshbhat** [comment]
New additions.
Updated the structure of progress.xml by adding "Period" under Results.
Simple Conformance tool is developed- SimpleTest.html
Test/second.php updated to remove foldername.

**Comment by niteeshbhat** [comment]
Updated mpdparsing.php to recognize intialisation segment.

**Comment by niteeshbhat** [comment]
Updated conformancetest.php to fix MPD file upload problem

**Comment by joywelt** [comment]
Already merged.

**Pull request closed without merging**
