### PR TITLE
Fixed issue #101 (Test framework proceeds for MPD conformance fails) and #102 (Suppress php errors)

### PR DESCRIPTION
**Pull request by niteeshbhat**
Fixed issue #101 (Test framework proceeds for MPD conformance fails) and #102 (Suppress php errors)

Changes in Test/second.php(for #101) and mpdprocessing.php(for #102)

### CODE REVIEW

**Comment by joywelt** [comment]
I tested the changes withe the test framework. The results are different. Is it expected or sth is wrong?
Please check again. Thanks.

**Comment by niteeshbhat** [comment]
I have repeated same commit with adding command.txt and config_file.txt. The issues are fixed. Please run again. Thanks.

**Comment by joywelt** [comment]
Thanks for the changes. I checked the code and it works well. 
One thing I noticed is that the test page also shows the difference of the execution time, like in the screenshots. Should we leave it like this? Or rather not compare/ ignore the execution time? @waqarz 
screenshot - 01262016 - 06 09 11 pm
screenshot - 01262016 - 06 08 31 pm

**Comment by waqarz** [comment]
This could be an enhancement; we are already doing post processing of the data, so we should replace the string "Total time: 1 seconds" to "Total time: x seconds", this way the comparison results would not show this.

**Pull request merged**
