### PR TITLE
Added a few features:

### PR DESCRIPTION
**Pull request by joywelt**
1. show cross-representation validation error log when there's an error.
2. add to progress.xml the timestamp in seconds w.r.t. UTC time. Clean the temp folders 5 mins after test completed or 30 mins after test started
3. show the broken URL lists when there are some segments missing during downloading
Cleaned up the code and updated the backend.

### CODE REVIEW

**Comment by richardbushell** [comment]
Did the cross-representation validation log addition throw up any answer to #127 please?

**Comment by joywelt** [comment]
@richardbushell The cross-representation validation log shows that for video representations, there is an overlapping between segments from different representations. There reasons are being discussed there #127 .

**Comment by richardbushell** [comment]
Can the Online Validator be updated straight away to include this log please? We are sure these segments are properly aligned, and the potential reason offered in #127 was incorrect.

**Comment by joywelt** [comment]
It's fixed in another commit and now online.

**Comment by richardbushell** [comment]
Great, yes have now seen that fix and re-tested. Works fine. Close if you wish.

**Pull request merged**
